spring:
  datasource:
    url: jdbc:h2:mem:boleto;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
management:
  security:
    enabled: false
eureka:
  client:
    defaultZone: ${services.eureka.url}
  instance:
    preferIpAddress: true
    statusPageUrlPath: /rest/actuator/info
    healthCheckUrlPath: /rest/actuator/health
  health:
    db:
      enabled: true
    defaults:
      enabled: true
server:
   servlet:
      context-path: /rest
   port: 8780