spring:
  application:
    name: desafio-gateway
  config:
    enabled: false
  cloud:
    discovery:
      enabled: false
server:
  port: 8080
zuul:
  ignoredServices: '*'
  routes:
    boleto-api:
      path: /rest/**
      serviceId: boleto-api
      stripPrefix: false
info:
  component: Edge Server
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${services.eureka.url}
    registerWithEureka: false
